// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnR4MX3apC-5C0K0FYO0q5VspEbqS_sYU',
    appId: '1:995746020234:web:f8e16ad28b18c76a316673',
    messagingSenderId: '995746020234',
    projectId: 'app-kopi',
    authDomain: 'app-kopi.firebaseapp.com',
    databaseURL: 'https://app-kopi-default-rtdb.firebaseio.com',
    storageBucket: 'app-kopi.appspot.com',
    measurementId: 'G-RQVSS34C06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCSF9fLzD9hIF-bwwCMEl-woZIoYIWZ3c',
    appId: '1:995746020234:android:5fed8b0b103f4051316673',
    messagingSenderId: '995746020234',
    projectId: 'app-kopi',
    databaseURL: 'https://app-kopi-default-rtdb.firebaseio.com',
    storageBucket: 'app-kopi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATa8yqXnqBYVMuSSGsEfvMPm6CYq_i3iU',
    appId: '1:995746020234:ios:2eb9fab2937b863c316673',
    messagingSenderId: '995746020234',
    projectId: 'app-kopi',
    databaseURL: 'https://app-kopi-default-rtdb.firebaseio.com',
    storageBucket: 'app-kopi.appspot.com',
    androidClientId: '995746020234-pi5ase2isglbnicls68qec8rr3580kpl.apps.googleusercontent.com',
    iosClientId: '995746020234-v9ahqccjcv2s32j0ac6l966pveq4kmg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATa8yqXnqBYVMuSSGsEfvMPm6CYq_i3iU',
    appId: '1:995746020234:ios:6c34ac0aa0ac2f1d316673',
    messagingSenderId: '995746020234',
    projectId: 'app-kopi',
    databaseURL: 'https://app-kopi-default-rtdb.firebaseio.com',
    storageBucket: 'app-kopi.appspot.com',
    androidClientId: '995746020234-pi5ase2isglbnicls68qec8rr3580kpl.apps.googleusercontent.com',
    iosClientId: '995746020234-7fbhmrd8t57i8qboe2va385ojc6s2icl.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopiApp.RunnerTests',
  );
}
